# This code is part of Qiskit.
#
# (C) Copyright IBM 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Nature Main Aer'
description: 'Installs Python Main Aer'
inputs:
  os:
    description: 'OS'
    required: true
  cache-path:
    description: 'Cache path'
    required: true
  cache-hit:
    description: 'Cache hit'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Aer from Main
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.16
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate psi4env
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          export DISABLE_CONAN=1
          sudo apt-get -y install nlohmann-json3-dev
          sudo apt-get -y install libspdlog-dev
          sudo apt-get -y install libmuparserx-dev
        fi
        git clone https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
        BASE_DIR=${{ inputs.cache-path }}
        build_from_main=true
        if [ "${{ inputs.cache-hit }}" == "true" ]; then
          pip_result=0
          pushd "${BASE_DIR}"
          python -m pip install *.whl && pip_result=$? || pip_result=$?
          popd
          if [ $pip_result == 0 ]; then
            echo 'Verifying cached Aer with tools/verify_wheels.py ...'
            verify_result=0
            pushd /tmp/qiskit-aer
            python tools/verify_wheels.py && verify_result=$? || verify_result=$?
            popd
            if [ $verify_result == 0 ]; then
              echo 'Cached Aer passed verification.'
              build_from_main=false
            else
              echo 'Cached Aer failed verification.'
            fi
          fi
        else
          mkdir -p ${BASE_DIR}
        fi
        if [ "$build_from_main" == "true" ]; then
          echo 'Create wheel file from main'
          pushd /tmp/qiskit-aer
          if [ "${{ inputs.os }}" == "windows-2019" ]; then
            python setup.py bdist_wheel -- -G 'Visual Studio 16 2019'
          else
            python setup.py bdist_wheel
          fi
          popd
          cp -rf /tmp/qiskit-aer/dist/*.whl "${BASE_DIR}"
          pushd "${BASE_DIR}"
          python -m pip install *.whl
          popd
        fi
      shell: bash
