# This code is part of a Qiskit project.
#
# (C) Copyright IBM 2021, 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install PSI4'
description: 'Installs conda PSI4'
inputs:
  os:
    description: 'OS'
    required: true
  python-version:
    description: 'Python version'
    required: true
runs:
  using: "composite"
  steps:
    - run : |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate psi4env
        py_requires_libecpint=("3.9" "3.10")
        if [[ "${{ inputs.os }}" == "ubuntu-latest" ]]; then
          for py_ver in "${py_requires_libecpint[@]}"; do
            if [[ "${{ inputs.python-version }}" == "$py_ver" ]]; then
              echo "Installing libecpint for Python $py_ver"
              conda install -c conda-forge libecpint
              break
            fi
          done
          echo $LD_LIBRARY_PATH
          echo $CONDA
          echo $CONDA_PREFIX
          export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
          echo $LD_LIBRARY_PATH
        fi
        echo "installs psi4 stable release"
        conda install -y psi4 python=${{ inputs.python-version }} -c conda-forge/label/libint_dev -c conda-forge
      shell: bash
