# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install PSI4'
description: 'Installs Miniconda with PSI4'
inputs:
  os:
    description: 'OS'
    required: true
  python-version:
    description: 'Python version'
    required: true
runs:
  using: "composite"
  steps:
    - run : |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate psi4env
        if [ "${{ inputs.os }}" == "windows-latest" ]; then
          conda install -y psi4=1.5a1.dev196 python=${{ inputs.python-version }} -c conda-forge -c psi4/label/dev
          psi4 --test
        else
          conda install -y psi4 python=${{ inputs.python-version }} -c psi4
          pip install -U numpy
        fi
      shell: bash