# This code is part of Qiskit.
#
# (C) Copyright IBM 2021, 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Deploy Docs

on:
  workflow_dispatch:

jobs:
  docs_publish:
    if: ${{ startsWith(github.ref, 'refs/heads/stable') && contains('["manoelmarques","mtreinish","stefan-woerner","woodsp-ibm"]', github.actor) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nature
        run: |
          pip install -e .[pyscf]
          pip install -U -c constraints.txt -r requirements-dev.txt
        shell: bash
      - name: Install Dependencies
        run: |
          pip install jupyter sphinx_rtd_theme qiskit-terra[visualization]
          sudo apt-get install -y pandoc graphviz
        shell: bash
      - name: Build and publish
        env:
          encrypted_rclone_key: ${{ secrets.encrypted_rclone_key }}
          encrypted_rclone_iv: ${{ secrets.encrypted_rclone_iv }}
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          echo "earliest_version: 0.1.0" >> releasenotes/config.yaml
          tools/ignore_untagged_notes.sh
          make html
          tools/deploy_documentation.sh
        shell: bash
  deploy-translatable-strings:
    if: ${{ startsWith(github.ref, 'refs/heads/stable') && contains('["manoelmarques","mtreinish","stefan-woerner","woodsp-ibm"]', github.actor) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter sphinx_rtd_theme qiskit-terra[visualization] torchvision tox
          sudo apt-get install -y pandoc graphviz
        shell: bash
      - name: Build and publish
        env:
          encrypted_deploy_po_branch_key: ${{ secrets.encrypted_deploy_po_branch_key }}
          encrypted_deploy_po_branch_iv: ${{ secrets.encrypted_deploy_po_branch_iv }}
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          echo "earliest_version: 0.1.0" >> releasenotes/config.yaml
          tools/ignore_untagged_notes.sh
          tools/deploy_translatable_strings.sh
        shell: bash
