# This code is part of a Qiskit project.
#
# (C) Copyright IBM 2021, 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Deploy Docs

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs_publish:
    if: ${{ startsWith(github.ref, 'refs/heads/stable') && contains('["mtreinish","woodsp-ibm","mrossinek","robertodr","matteoacrossi"]', github.actor) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install jupyter
          sudo apt-get install -y pandoc
        shell: bash
      - name: Install Nature
        run: |
          pip install -e .[pyscf,mpl,sparse]
          pip install -U -c constraints.txt -r requirements-dev.txt
        shell: bash
      - name: Build docs
        env:
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          echo "earliest_version: 0.1.0" >> releasenotes/config.yaml
          tools/ignore_untagged_notes.sh
          make html
        shell: bash
      - name: Bypass Jekyll Processing # Necessary for setting the correct css path
        run: touch docs/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html/
          clean-exclude: |
            locale/*
